config/routes.rb
WebQueue::Application.routes.draw do
  resources :countries

  resources :sports

  resources :leagues
  get "leagues/sport/:id" => "leagues#sport", :as => "leagues_sport"

  resources :tasks

  get "queue/status" => "queue#index", :as => "queue_status"
  get "queue/stop" => "queue#stop"
  get "queue/start" => "queue#start"

  resources :queue

  root :to => "home#index"

end

app/models/league.rb
class League
  include Mongoid::Document
  field :title, type: String
  field :alias, type: String
  field :type, type: Integer

  belongs_to :sport, :class_name => 'Sport'
  belongs_to :country, :class_name => 'Country'

  validates_uniqueness_of :type
  validates_presence_of :type, :title, :alias, :sport, :country


  def default
    self.data ||= {}
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all.sort(:type => 1)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def sport
    @leagues = League.where(:sport => params[:id]).sort(:type => 1)

    respond_to do |format|
      format.html { render action: "index" }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.json
  def new
    @league = League.new
    @sports = Sport.all.map { |sport| [sport.title, sport._id.to_s] }
    @countries = Country.all.sort :title => 1
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
    @sports = Sport.all.map { |sport| [sport.title, sport._id.to_s] }
    @countries = Country.all.sort(:title => 1).map { |country| [country.title, country._id.to_s] }
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(params[:league])
    @league[:sport] = Moped::BSON::ObjectId params[:sport]
    @league[:country] = Moped::BSON::ObjectId params[:country]

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
      else
        @sports = Sport.all.map { |sport| [sport.title, sport._id.to_s] }
        format.html { render action: "new" }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.json
  def update
    @league = League.find(params[:id])
    @league[:sport] = Moped::BSON::ObjectId params[:sport]
    @league[:country] = Moped::BSON::ObjectId params[:country]

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
    <% if @league.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

          <ul>
            <% @league.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="fields five columns">
        <div class="row">
          <div class="two column"><%= label_tag(:sport, "Sport:", :class => "right inline") %></div>
          <div class="ten columns"><%= select_tag(:sport, options_for_select(@sports, (@league[:sport_id] unless @league.new_record?))) %></div>
        </div>
        <div class="row">
          <div class="two column"><%= f.label :type, "Type:", :class => 'right inline' %></div>
          <div class="ten column"><%= f.number_field :type, :class => "two" %></div>
        </div>
        <div class="row">
          <div class="two column"><%= f.label :title, "Title:", :class => 'right inline' %></div>
          <div class="ten columns"><%= f.text_field :title %></div>
        </div>
        <div class="row">
          <div class="two column"><%= label_tag(:country, "Country:", :class => "right inline") %></div>
          <div class="ten columns"><%= select_tag(:country, options_for_select(@countries, (@league[:country_id] unless @league.new_record?))) %></div>
        </div>
        <div class="row">
          <div class="two column"><%= f.label :alias, "Alias:", :class => 'right inline' %></div>
          <div class="ten columns"><%= f.text_field :alias %></div>
        </div>
        <div class="actions row">
          <div class="two column"></div>
          <div class="ten columns"><%= f.submit :class => 'button radius' %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/leagues/_list.html.erb
<table class="twelve">
  <thead>
  <tr>
    <th class="one text-center">Type</th>
    <th class="three">Title</th>
    <th class="three">Country</th>
    <th class="three">Alias</th>
    <th class="two text-center">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% leagues.each do |league| %>
      <tr>
        <td class="text-center"><%= league.type %></td>
        <td><%= league.title %></td>
        <td><%= league.country.title unless league.country.nil? %></td>
        <td><%= league.alias %></td>
        <td class="text-center"><%= link_to 'Show', league %> |
          <%= link_to 'Edit', edit_league_path(league) %> |
          <%= link_to 'Destroy', league, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/leagues/edit.html.erb
<% title "Editing league" %>
<h1><%= yield :title %> | <%= link_to "List", leagues_path, :class => 'appendix' %></h1>

<%= render 'form' %>

app/views/leagues/index.html.erb
<% title "Listing leagues" %>
<h1><%= yield :title %> | <%= link_to "Add new", new_league_path, :class => 'appendix' %></h1>

<%= render 'list', :leagues => @leagues %>

app/views/leagues/new.html.erb
<% title "New league" %>
<h1><%= yield :title %> | <%= link_to "List", leagues_path, :class => 'appendix' %></h1>

<%= render 'form' %>

app/views/leagues/show.html.erb
<% title @league.title %>
<h1><%= yield :title %> |
  <span class="appendix"><%= link_to 'Edit', edit_league_path(@league) %></span> |
  <span class="appendix"><%= link_to 'List', leagues_path %></span>
</h1>

<% if (notice) %>
    <div class="alert-box success"><%= notice %></div>
<% end %>
<p>
  <b>Title:</b>
  <%= @league.title %>
</p>

<p>
  <b>Alias:</b>
  <%= @league.alias %>
</p>

<p>
  <b>Type:</b>
  <%= @league.type %>
</p>