config/routes.rb
WebQueue::Application.routes.draw do
  resources :countries

  resources :sports

  resources :leagues
  get "leagues/sport/:id" => "leagues#sport", :as => "leagues_sport"

  resources :tasks

  get "queue/status" => "queue#index", :as => "queue_status"
  get "queue/stop" => "queue#stop"
  get "queue/start" => "queue#start"

  resources :queue

  root :to => "home#index"

end

app/models/sport.rb
class Sport
  include Mongoid::Document
  field :type, type: Integer
  field :title, type: String

  has_many :leagues, :inverse_of => :sport
  validates_uniqueness_of :type
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sports }
    end
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
    @sport = Sport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/new
  # GET /sports/new.json
  def new
    @sport = Sport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /sports/1/edit
  def edit
    @sport = Sport.find(params[:id])
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(params[:sport])

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render json: @sport, status: :created, location: @sport }
      else
        format.html { render action: "new" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sports/1
  # PUT /sports/1.json
  def update
    @sport = Sport.find(params[:id])

    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
    <% if @sport.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

          <ul>
            <% @sport.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="fields five columns">
        <div class="row">
          <div class="two column"><%= f.label :type, "Type:", :class => 'right inline' %></div>
          <div class="ten column"><%= f.number_field :type, :class => "two" %></div>
        </div>
        <div class="row">
          <div class="two column"><%= f.label :title, "Title:", :class => 'right inline' %></div>
          <div class="ten columns"><%= f.text_field :title %></div>
        </div>
        <div class="actions row">
          <div class="two column"></div>
          <div class="ten columns"><%= f.submit :class => 'button radius' %></div>
        </div>
      </div>
    </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<% title "Listing sports" %>
<h1><%= yield :title %> | <%= link_to "Add new", new_sport_path, :class => 'appendix' %></h1>

<table class="twelve">
  <thead>
  <tr>
    <th class="one text-center">Type</th>
    <th class="three">Title</th>
    <th class="two text-center">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sports.each do |sport| %>
      <tr>
        <td class="text-center"><%= sport.type %></td>
        <td><%= sport.title %></td>
        <td class="text-center"><%= link_to 'Show', sport %> |
          <%= link_to 'Edit', edit_sport_path(sport) %> |
          <%= link_to 'Destroy', sport, method: :delete, data: {confirm: 'Are you sure?'} %> |
          <%= link_to 'Leagues', leagues_sport_path(sport) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/sports/new.html.erb
<% title "New sport" %>
<h1><%= yield :title %> | <%= link_to "List", sports_path, :class => 'appendix' %></h1>

<%= render 'form' %>

app/views/sports/show.html.erb
<div class="alert-box success">
  <%= notice %>
  <a href="" class="close">×</a>
</div>

<p>
  <b>Title:</b>
  <%= @sport.title %>
</p>
<p>
  <b>Type:</b>
  <%= @sport.type %>
</p>


<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>