config/routes.rb
WebQueue::Application.routes.draw do
  resources :countries

  resources :sports

  resources :leagues
  get "leagues/sport/:id" => "leagues#sport", :as => "leagues_sport"

  resources :tasks

  get "queue/status" => "queue#index", :as => "queue_status"
  get "queue/stop" => "queue#stop"
  get "queue/start" => "queue#start"

  resources :queue

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html"> <!--<![endif]-->
<head>
  <meta charset="utf-8"/>
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title>Web Soccer Queue - <%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  <!-- Included CSS Files -->
  <%= stylesheet_link_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,200&subset=latin,cyrillic' rel='stylesheet' type='text/css'>


  <%= csrf_meta_tags %>
</head>
<body>


<!-- Header and Nav -->

<nav class="top-bar">
  <ul>
    <li class="name"><a href="#"><span>Tony Inc.</span></a></li>
    <li class="toggle-topbar"><a href="#"></a></li>
  </ul>
  <section>
    <ul class="left">
      <li><a href="#">Link</a></li>
    </ul>

    <ul class="right">
      <li><a href="#">Link</a></li>
    </ul>
  </section>
</nav>

<!-- End Header and Nav -->


<div class="row">

  <!-- Nav Sidebar -->
  <!-- This is source ordered to be pulled to the left on larger screens -->
  <div id="side-nav" class="one column">

    <ul class="side-nav">
      <li class="<%= is_active?('queue') %>">
        <%= link_to queue_status_path do %>
            <i class="icon icon-2x icon-dashboard"></i>Queue
        <% end %>
      </li>
      <li class="<%= is_active?('tasks') %>">
        <%= link_to tasks_path do %>
            <i class="icon icon-2x icon-tasks"></i>Task info
        <% end %>
      </li>
      <li class="<%= is_active?('params') %>">
        <%= link_to tasks_path do %>
            <i class="icon icon-2x icon-hdd"></i>Config
        <% end %>
      </li>
      <li class="<%= is_active?('stats') %>">
        <%= link_to tasks_path do %>
            <i class="icon icon-2x icon-bar-chart"></i>Stats
        <% end %>
      </li>
      <li class="<%= is_active?('sports') %>">
        <%= link_to sports_path do %>
            <i class="icon icon-2x icon-bar-chart"></i>Sports
        <% end %>
      </li>
      <li class="<%= is_active?('leagues') %>">
        <%= link_to leagues_path do %>
            <i class="icon icon-2x icon-bar-chart"></i>Leagues
        <% end %>
      </li>
      <li class="<%= is_active?('countries') %>">
        <%= link_to countries_path do %>
            <i class="icon icon-2x icon-bar-chart"></i>Countries
        <% end %>
      </li>
    </ul>

  </div>
  <!-- Main Content Section -->
  <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
  <div id="content" class="eleven columns">
    <%= yield %>
  </div>


</div>


<!-- Footer -->

<footer class="row">
  <div class="twelve columns">
    <hr/>
    <div class="row">
      <div class="six columns">
        <p>&copy; Tony <%= Time.now.year %></p>
      </div>
      <div class="six columns">
        <ul class="inline-list right">
          <li><a href="#">Section 1</a></li>
          <li><a href="#">Section 2</a></li>
          <li><a href="#">Section 3</a></li>
          <li><a href="#">Section 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!-- Included JS Files  -->
<%= javascript_include_tag "application" %>
</body>
</html>